---
kind: pipeline
name: default

clone:
  depth: 42

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./libraries/vendor
        - ./administrator/components/com_media/node_modules
      cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache

  - name: composer
    image: joomlaprojects/docker-tools:develop
    depends_on: [ restore-cache ]
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest

  - name: phpcs
    image: joomlaprojects/docker-images:php7.2
    depends_on: [ composer ]
    commands:
      - echo $(date)
      - ./libraries/vendor/bin/phpcs --extensions=php -p --standard=libraries/vendor/joomla/cms-coding-standards/lib/Joomla-CMS .
      - echo $(date)

  - name: npm
    image: joomlaprojects/docker-tools:develop
    depends_on: [ phpcs ]
    commands:
      - npm ci --unsafe-perm

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on: [ npm ]
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./libraries/vendor
        - ./administrator/components/com_media/node_modules
      cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache

  - name: api-tests
    depends_on: [ npm ]
    image: joomlaprojects/docker-systemtests:latest
    commands:
      - bash tests/Codeception/drone-api-run.sh "$(pwd)"

  - name: artifacts-system-tests	
    image: cschlosser/drone-ftps	
    depends_on: [ api-tests ]	
    environment:	
      FTP_USERNAME:	
        from_secret: ftpusername	
      FTP_PASSWORD:	
        from_secret: ftppassword	
      PLUGIN_HOSTNAME: ci.joomla.org:21	
      PLUGIN_SRC_DIR: /tests/Codeception/_output/	
      PLUGIN_DEST_DIR: /artifacts	
      PLUGIN_SECURE: false	
      PLUGIN_EXCLUDE: ^\.git/$	
    commands:	
      - export PLUGIN_DEST_DIR=$PLUGIN_DEST_DIR/$DRONE_REPO/$DRONE_BRANCH/$DRONE_PULL_REQUEST/system-tests/$DRONE_BUILD_NUMBER	
      - echo https://ci.joomla.org:444$PLUGIN_DEST_DIR	
      - /bin/upload.sh	
    when:	
      status:	
      - failure	

branches:
  exclude: [ l10n_* ]

volumes:
- name: cache
  host:
    path: /tmp/cache
- name: reference
  host:
    path: /tmp/reference

services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla

  - name: memcached
    image: memcached:alpine

---
kind: signature
hmac: eccb15c09f54a3b58a9564f1cc53a5fe06e7d90f90e5118971f2913f84fec7e6

...
