---
kind: pipeline
name: Codequality

platform:
  os: linux
  arch: amd64

---
kind: pipeline
name: PHP 8.0

platform:
  os: linux
  arch: amd64

steps:
  - name: composer
    image: joomlaprojects/docker-images:php8.0
    commands:
      - php -v
      - composer --version
      - composer install
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache

  - name: prepare
    image: joomlaprojects/docker-images:php8.0
    commands:
      - php -v
      - sleep 20
      - "mysql --host=mysql --user=joomla_ut --password=joomla_ut --database=joomla_ut < \"tests/unit/schema/mysql.sql\""
      - "psql -h postgres -d joomla_ut -U joomla_ut -a -f \"tests/unit/schema/postgresql.sql\""
    environment:
      PGPASSWORD: joomla_ut

  - name: PHPUnit
    image: joomlaprojects/docker-images:php8.0
    commands:
      - phpunit --version
      - phpunit --configuration phpunit.xml.php8 --verbose --debug

services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_USER: joomla_ut

  - name: postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: joomla_ut
      POSTGRES_PASSWORD: joomla_ut
      POSTGRES_USER: joomla_ut
    ports:
      - 5432

  - name: memcached
    image: memcached:alpine

  - name: redis
    image: redis:alpine

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache


services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_USER: joomla_ut

  - name: postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: joomla_ut
      POSTGRES_PASSWORD: joomla_ut
      POSTGRES_USER: joomla_ut
    ports:
      - 5432

  - name: memcached
    image: memcached:alpine

  - name: redis
    image: redis:alpine

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache
---
kind: signature
hmac: 95b8174da6bfeba896cdcc2293912e8f5cc32d4129e50ce6541c6b49b36d0877

...
