---
kind: pipeline
name: default

clone:
  depth: 42

steps:
  - name: phpcs
    image: joomlaprojects/docker-images:phpcs1.5
    commands:
      - echo $(date)
      - /usr/local/vendor/bin/phpcs --report=full --encoding=utf-8 --extensions=php -p --standard=build/phpcs/Joomla .
      - echo $(date)

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./tests/javascript/node_modules
        - ./tests/codeception/vendor
      cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache

  - name: javascript
    image: joomlaprojects/docker-images:systemtests
    commands:
      - echo $(date)
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - cd tests/javascript
      - npm install
      - cd ../..
      - tests/javascript/node_modules/karma/bin/karma start karma.conf.js --single-run
      - echo $(date)

  - name: updateto4
    image: joomlaprojects/docker-images:systemtests
    commands:
      - echo $(date)
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - apache2ctl -D FOREGROUND &
      - /etc/init.d/mysql start
      - sleep 5
      - mysqladmin ping -hlocalhost
      - mysql -uroot -e "create user 'joomla_test'@'localhost' identified by 'joomla_test'"
      - mysql -uroot -e "grant all privileges on *.* to 'joomla_test'@'localhost'"
      - cd tests/javascript
      - npm install
      - ./node_modules/.bin/selenium-standalone install --drivers.chrome.version=77.0.3865.40 --drivers.chrome.baseURL=https://chromedriver.storage.googleapis.com
      - ./node_modules/.bin/selenium-standalone start --drivers.chrome.version=77.0.3865.40 --drivers.chrome.baseURL=https://chromedriver.storage.googleapis.com >> ../../selenium.log 2>&1 &
      - cd ../codeception
      - sed -i "s/GITHUB_ACCESS_TOKEN/$GITHUB_TOKEN/g" composer.json
      - composer install
      - cd ../..
      - cp RoboFile.dist.ini RoboFile.ini
      - ./tests/codeception/vendor/bin/robo run:joomla4
      - echo $(date)
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
       rebuild: true
       mount:
        - ./tests/javascript/node_modules
        - ./tests/codeception/vendor
       cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache

  - name: artifacts-system-tests
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      PLUGIN_HOSTNAME: ci.joomla.org:21
      PLUGIN_SRC_DIR: /tests/codeception/_output/
      PLUGIN_DEST_DIR: /artifacts
      PLUGIN_SECURE: false
      PLUGIN_EXCLUDE: ^\.git/$
    commands:
      - export PLUGIN_DEST_DIR=$PLUGIN_DEST_DIR/$DRONE_REPO/$DRONE_BRANCH/$DRONE_PULL_REQUEST/system-tests/$DRONE_BUILD_NUMBER
      - echo https://ci.joomla.org:444$PLUGIN_DEST_DIR
      - /bin/upload.sh
    when:
      status:
        - failure

  - name: analysis3x
    image: rips/rips-cli:3.2.2
    when:
      branch: staging
    commands:
      - export RIPS_BASE_URI='https://api.rips.joomla.org'
      - if [ $DRONE_REPO_NAMESPACE != 'joomla' ]; then echo "The analysis check only run on the main repos"; exit 0; fi
      - rips-cli rips:list --table=scans -n -p filter='{"__and":[{"__lessThan":{"percent":100}}]}'
      - rips-cli rips:scan:start -G -a 1 -t 1 -p $(pwd) -t 1 -R -k -T $DRONE_REPO_NAMESPACE-$DRONE_BRANCH ||  { echo "Please contact the security team at security@joomla.org"; exit 1; }
    environment:
      RIPS_EMAIL:
        from_secret: RIPS_EMAIL
      RIPS_PASSWORD:
        from_secret: RIPS_PASSWORD

volumes:
- name: cache
  host:
    path: /tmp/cache

branches:
  exclude: [ l10n_* ]

---
kind: signature
hmac: 17625de319fca0bf4f7f52d9f38ad8b50cb67ce6b9ed4e4d6b6b82e91f3c8e35

...
