---
kind: pipeline
name: default

clone:
  depth: 42

steps:
  - name: phpcs
    image: joomlaprojects/docker-phpcs
    commands:
      - echo $(date)
      - /root/.composer/vendor/bin/phpcs --report=full --encoding=utf-8 --extensions=php -p --standard=build/phpcs/Joomla .
      - echo $(date)

  - name: restore-cache
    image: drillster/drone-volume-cache
    depends_on: [ phpcs ]
    settings:
      restore: true
      mount:
        - ./tests/javascript/node_modules
      cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache


  - name: prepare
    image: joomlaprojects/docker-tools:develop
    depends_on: [ restore-cache ]
    commands:
      - composer install --no-progress --no-suggest
      - cd tests/javascript
      - npm install

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on: [ prepare ]
    settings:
       rebuild: true
       mount:
        - ./tests/javascript/node_modules
       cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache

  - name: javascript
    image: joomlaprojects/docker-systemtests:latest
    depends_on: [ rebuild-cache ]
    commands:
      - echo $(date)
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - tests/javascript/node_modules/karma/bin/karma start karma.conf.js --single-run
      - echo $(date)

  - name: php53-unit
    depends_on: [ rebuild-cache ]
    image: alterway/php:5.3-apache
    environment:
      PHP_php5enmod: 'gd ldap mbstring memcached mysql mysqli pdo_mysql redis soap zip ftp sockets'
      PHP__display_errors: On
      PHP__memory_limit: 512M
    commands:
      - php -v
      - php -i
      - ./libraries/vendor/bin/phpunit

  - name: php54-unit
    depends_on: [ rebuild-cache ]
    image: alterway/php:5.4-apache
    environment:
      PHP__display_errors: On
      PHP__memory_limit: 512M
    commands:
      - php -v
      - ./libraries/vendor/bin/phpunit

  - name: php55-unit
    depends_on: [ rebuild-cache ]
    image: alterway/php:5.5-apache
    environment:
      PHP__display_errors: On
      PHP__memory_limit: 512M
    commands:
      - php -v
      - ./libraries/vendor/bin/phpunit

  - name: php56-unit
    depends_on: [ rebuild-cache ]
    image: alterway/php:5.6-apache
    environment:
      PHP__display_errors: On
      PHP__memory_limit: 512M
    commands:
      - php -v
      - ./libraries/vendor/bin/phpunit

  - name: php70-unit
    depends_on: [ rebuild-cache ]
    image: alterway/php:7.0-apache
    environment:
      PHP__display_errors: On
      PHP__memory_limit: 512M
    commands:
      - php -v
      - ./libraries/vendor/bin/phpunit

  - name: php71-unit
    depends_on: [ rebuild-cache ]
    image: alterway/php:7.1-apache
    environment:
      PHP__display_errors: On
      PHP__memory_limit: 512M
    commands:
      - php -v
      - ./libraries/vendor/bin/phpunit

  - name: php72-unit
    depends_on: [ rebuild-cache ]
    image: php:7.2
    commands:
      - php -v
      - ./libraries/vendor/bin/phpunit

  - name: php73-unit
    depends_on: [ rebuild-cache ]
    image: php:7.3
    commands:
      - php -v
      - ./libraries/vendor/bin/phpunit

  - name: php74-unit
    depends_on: [ rebuild-cache ]
    image: phpdaily/php:7.4-dev
    errignore: true
    commands:
      - php -v
      - ./libraries/vendor/bin/phpunit

  - name: php80-unit
    depends_on: [ rebuild-cache ]
    image: phpdaily/php:8.0-dev
    errignore: true
    commands:
      - php -v
      - ./libraries/vendor/bin/phpunit

  - name: analysis3x
    image: rips/rips-cli:1.2.1
    depends_on: [ php73-unit ]
    when:
      branch: staging
    commands:
      - export RIPS_BASE_URI='https://api.rips.joomla.org'
      - if [ $DRONE_REPO_NAMESPACE != 'joomla' ]; then echo "The analysis check only run on the main repos"; exit 0; fi
      - rips-cli rips:scan:start -a 1 -t 1 -p $(pwd) -t 1 -R -k -T $DRONE_REPO_NAMESPACE-$DRONE_BRANCH ||  { echo "Please contact the security team at security@joomla.org"; exit 1; }
    environment:
      RIPS_USERNAME:
        from_secret: RIPS_USERNAME
      RIPS_PASSWORD:
        from_secret: RIPS_PASSWORD

volumes:
- name: cache
  host:
    path: /tmp/cache

services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla

  - name: memcached
    image: memcached:alpine

  - name: redis
    image: redis:alpine

branches:
  exclude: [ l10n_* ]
---
kind: signature
hmac: 9b8422fde5eb59d73506c403cb5738486f3d322c3b9f6f2550cff4d328fb0599

...
