fail_on_violations: true

scss:
  enabled: true
  config_file: scss-lint.yml

scss-lint:
  version: 0.59.0

# Disable hound default linters
eslint:
  enabled: false

jshint:
  enabled: false

ruby:
  enabled: false
