# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_UNIT_TESTS="yes"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: INSTALL_APC="yes" crappy=true
    - php: 5.3
      env: INSTALL_APC="yes" crappy=false
    - php: 5.4
      env: INSTALL_APC="yes"
    - php: 5.5
      env: INSTALL_APCU="yes"
    - php: 5.6
      env: INSTALL_APCU="yes"
    - php: 7.0
      env: INSTALL_APCU="yes" INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled apcu_bc install until https://github.com/travis-ci/travis-ci/issues/5207 is resolved
    - php: 7.1
      env: INSTALL_APCU="yes" INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled apcu_bc install until https://github.com/travis-ci/travis-ci/issues/5207 is resolved
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        - postgresql
        - redis-server
      env: INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" # Disabled items that currently do not work in travis-ci hhvm
  allow_failures:
    - php: hhvm

before_install:
  - |
    if [[ $crappy ]]; then
      INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      echo date.timezone = "" >> $INI
      echo memory_limit = 1024M >> $INI
      echo disable_functions = parse_ini_file,exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source >> $INI
      echo session.gc_probability = 0 >> $INI
      echo opcache.enable_cli = 1 >> $INI
      echo hhvm.jit = 0 >> $INI
      echo apc.enable_cli = 0 >> $INI
    fi

services:
  - memcache
  - memcached
  - redis-server

before_script:
  # Make sure all dev dependencies are installed
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then bash build/travis/unit-tests.sh $PWD; fi

script:
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml; fi

branches:
  except:
    - 2.5.x
