name: Cron to update the Browserlist DB

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Runs on the first day of every month at 03:00
    - cron:  '0 0 * * SUN'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    if: (github.event_name == 'schedule' && github.repository == 'joomla/joomla-cms') || (github.event_name != 'schedule')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # We need the full depth to create / update the pull request against the main repo
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Udate the browserlist db
        run: npm ci --ignore-scripts && npm run browserlist:update

      - name: Create pull request
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          gh pr list -R joomla/joomla-cms --state open --author joomla-browserlist-bot -S "Browserlist Update" | grep -v "No pull" || \
          gh pr create --title "Browserlist Update" --body "Automatically created pull request based on core-browserlist changes" -R joomla/joomla-cms --base 4.2-dev
