name: Create translation pull request

on:
  push:
    branches: [ translation ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Only run this action the translation-bot repository in the translation branch
    if: ${{ github.repository == 'joomla-translation-bot/joomla-cms' && github.ref == 'refs/heads/translation' }}

    steps:
      - uses: actions/checkout@v2
        # We need the full depth to create / update the pull request against the main repo
        with:
          fetch-depth: 0

      - name: Fetch latest cms changes
        run: |
          git config user.name Translation Bot
          git config user.email release+translation-bot@joomla.org
          git remote add upstream https://github.com/joomla/joomla-cms.git
          git fetch upstream
          git checkout --progress --force -B test refs/remotes/origin/test          
          git rebase upstream/4.0-dev

      - name: Fetch and extract translations
        run: |
          cd ..
          wget -nv "https://github.com/joomla/core-translations/archive/refs/heads/main.zip"
          unzip main.zip

      - name: Syncing directories
        # We use a simple copy paste syntax here if needed customization for different directories
        run: |
          git switch test
          cd ..
          SYNC_VERION="v4"
          ls -l
          ls -l core-translations-main
          ls -l joomla-cms

          SYNC_PATH="build/media_source/system/js/fields/calendar-locales/"
          echo ${SYNC_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete --exclude="*en-GB*" core-translations-main/joomla_${SYNC_VERION}/translations/core/${SYNC_PATH} joomla-cms/${SYNC_PATH} 
          ls -l joomla-cms/${SYNC_PATH}
          
          SYNC_PATH="installation/language/"
          echo ${SYNC_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete --exclude="*en-GB*" core-translations-main/joomla_${SYNC_VERION}/translations/core/${SYNC_PATH} joomla-cms/${SYNC_PATH} 
          ls -l joomla-cms/${SYNC_PATH}
          
      - name: Create commit
        run: |
          git config user.name Translation Bot
          git config user.email release+translation-bot@joomla.org
          git status
          git checkout test
          git switch test
          git commit -am "Language update"
          git push --force
          
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}      
        run: |
          gh pr list -R joomla/joomla-cms --state open --author joomla-translation-bot -S "Translation Update" | grep -v "No pull" || \
            gh pr create --title "Translation Update" --body "Automatically created pull request based on core-translation repository changes" -R joomla/joomla-cms --base 4.0-dev
